# Generated by Django 4.1.3 on 2022-11-27 11:25

from django.db import migrations, models

import project.core.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Title"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        upload_to=project.core.utils.models.file_upload_to,
                        verbose_name="Image",
                    ),
                ),
                ("url", models.URLField(max_length=256, verbose_name="URL")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(db_index=True, verbose_name="Published At"),
                ),
            ],
        ),
    ]
