# Generated by Django 4.1.3 on 2022-11-27 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.core.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achieve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Title"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon",
                    models.ImageField(
                        upload_to=project.core.utils.models.file_upload_to,
                        verbose_name="Icon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAchieve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "achieve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achieves.achieve",
                        verbose_name="Achieve",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
